import About from "components/About/About";
import Header from "components/header/Header";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Diego Díaz M - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="favicon.png" type="image/png" />
      </Head>
      <div>
        <Header />
        <About />
      </div>
    </div>
  );
}
