import About from "components/About/About";
import Footer from "components/Footer/Footer";
import Header from "components/header/Header";
import Projects from "components/Projects/Projects";
import Skills from "components/Skills/Skills";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Diego Díaz M - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/assets/favicon.ico" type="image/ico" />
      </Head>
      <div>
        <Header />
        <About />
        <Skills />
        <Projects />
        <Footer />
      </div>
    </div>
  );
}
